git:
  depth: 3

jobs:
  include:
  - name: Flutter tests, stable channel
    os: linux
    dist: trusty
    language: ruby
    script: "./tool/travis_flutter_script.sh"
    before_script:
    - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
    - "./flutter/bin/flutter doctor"
    - chmod +x tool/travis_*_script.sh
    env: FLUTTER_VERSION=stable

  - name: Flutter tests, beta channel
    os: linux
    dist: trusty
    language: ruby
    before_script:
    - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
    - "./flutter/bin/flutter doctor"
    - chmod +x tool/travis_*_script.sh
    script: "./tool/travis_flutter_script.sh"
    env: FLUTTER_VERSION=beta

  - name: Dart tests, stable channel
    language: dart
    script: "./tool/travis_dart_script.sh"
    dart: stable

  - name: Dart tests, dev channel
    language: dart
    script: "./tool/travis_dart_script.sh"
    dart: dev

  allow_failures:
  - env: FLUTTER_VERSION=beta
  - dart: dev


cache:
  directories:
  - "$HOME/shared/.pub-cache"

notifications:
  email: brogdon+github@gmail.com

branches:
  only:
  - master
