name: dartpad_test
description: Utilities to make testing code snippets in DartPad easier.

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  # The test team recommends pinning matcher
  matcher: ^0.12.5

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.9
