name: dartpad_test
description: Utilities to make testing code snippets in DartPad easier.

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

  # The test team recommends pinning matcher
  matcher: 0.12.5
