name: dartpad_test
description: Utilities to make testing code snippets in DartPad easier.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/RedBrogdon/dartpad_test

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  # The test team recommends pinning matcher
  matcher: ^0.12.5

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.9
