name: dartpad_test
description: Utilities to simplify testing of Dart code snippets in DartPad.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/RedBrogdon/dartpad_test

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  matcher: ^0.12.6

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
