name: dartpad_flutter_test
description: A new Flutter package project.
version: 0.0.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/RedBrogdon/dartpad_test


environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartpad_test:
    git:
      url: git://github.com/RedBrogdon/dartpad_test.git
      path: packages/dartpad_test

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
